service: okta-api-keypalive
frameworkVersion: '3'
configValidationMode: error
useDotenv: true
plugins:
  - serverless-webpack
  - serverless-dotenv-plugin

provider:
  name: aws
  stage: ${env:ENVIRONMENT}
  region: us-east-1
  vpc:
    securityGroupIds:
      - sg-888294ed
    subnetIds:
      - subnet-f2c2dfda # us-east-1a
      - subnet-1508db62 # us-east-1b
      - subnet-3fd94266 # us-east-1c
  stackTags:
    Name: ${env:PROJECT_NAME}-${self:custom.environmentMap.${env:ENVIRONMENT}}
    owner: devops-engineering-team@cru.org
    application: ${env:PROJECT_NAME}
    env: ${self:custom.environmentMap.${env:ENVIRONMENT}}
    managed_by: serverless-framework
    function: lambda
  iam:
    role:
      managedPolicies:
        - ${env:SSM_POLICY_ARN}
  layers:
    - arn:aws:lambda:us-east-1:072686360478:layer:node-16_14_2:1

package:
  individually: true
  patterns:
    - '!.webpack/**'
    - '!test/**'
    - '!**/*.test.js'
    - '!.deployment/**'

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
    packager: yarn
    excludeRegex: \.ts|test|\.map
  environmentMap:
    production: prod
    staging: stage
    development: dev
    lab: lab

functions:
  keypalive:
    handler: handlers/keypalive.handler
    memorySize: 128
    timeout: 30
    description: Function to periodically call Okta api with various keys to prevent expiration.
    events:
      # Run daily at 12:00a
      - schedule: cron(0 0 * * ? *)
